config/routes.rb
Mustrd::Application.routes.draw do

  root to: 'products#homepage'
  
  devise_for :users
  resource :users, only: [:show]

  resources :products
  resources :carts
  resources :charges

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_and_belongs_to_many :products

	def count
		products.count
	end


	def items
		products.group_by(&:id).map do |id,product_group|
			LineItem.new(product_group)
		end
	end

	def total
		memo = 0
		items.each do |i|
			memo += i.amount
		end
		memo
	end

end


class LineItem
	def initialize(product_group)
		@item = product_group[0]
		@qty = product_group.count
	end

	def name
		@item.name
	end

	def price
		@item.price
	end

	def qty
		@qty
	end

	def amount
		@item.price * @qty
	end

	def image
		@item.image.url(:thumbnail)
	end


end

class BigDecimal
	def in_pounds
		sprintf "£%.2f", self
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	after_create :send_confirmation_email

	def send_confirmation_email
		OrderNotifier.confirmation_email(number_of_items).deliver!
	end
end

app/models/product.rb
class Product < ActiveRecord::Base

	has_and_belongs_to_many :carts

	has_attached_file :image, storage: :s3,
							  bucket: "mustrd-123456",
							  styles: { thumb: '140x140>', thumbnail: '45x45>' }

	def formatted_price
		sprintf "£%.2f", price
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :create_empty_cart
  helper_method :current_cart
  
  def create_empty_cart
    session[:cart_id] ||= Cart.create.id
  end
  
  def current_cart
    Cart.find(session[:cart_id])
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def show
		@items = current_cart.items
	end

	def update
		product = Product.find params[:cart][:product_id]
		current_cart.products << product
		redirect_to product_path(product)
	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @display_amount = current_cart.total.in_pounds
	  @amount = (current_cart.total * 100).to_i

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'gbp'
	  )

	  Order.create(:number_of_items => current_cart.count)
	  session[:cart_id] = nil
	  create_empty_cart

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def homepage
		@products = Product.all
		@hide_sidebar = true
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
		@product = Product.new
	end

	def create
		product = Product.create(params[:product].permit(:name, :description, :quantity, :price, :image))
		redirect_to product_path(product)
		
		rescue AWS::S3::Errors::ResquestTimeout
		     flash[:notice] = "Upload timeout"
		     redirect_to 'new'
	end



	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(params[:product].permit(:name, :description, :quantity, :price, :image))
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		product = Product.find(params[:id]).destroy
		redirect_to products_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def poupon
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h2>Your Cart</h2>

<table class="col-md-6">
	<% @items.each do |item| %>
		<tr>
			<td>Qty: <%= item.qty %></td>
			<td id='product-image'><%= image_tag item.image %></td>
			<td><%= item.name %></td>
			<td><%= item.price.in_pounds %></td>
			<td class="item-price"><%= item.amount.in_pounds %></td>
		</tr>
	<% end %>

	<tr class="total_line">
		<td colspan="4" align="left">Total</td>
		<td class="total-cell"><%= current_cart.total.in_pounds %></td>
	</tr>
</table>


<div><%= button_to 'Checkout', new_charge_path, :method => :get, class: 'btn btn-default btn-lg btn-block' %></div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @display_amount %></strong>!</h2>

app/views/charges/index.html.erb
<h1>Charges#index</h1>
<p>Find me in app/views/charges/index.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: <%=current_cart.total.in_pounds %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Your order"
          data-amount="<%=current_cart.total * 100 %>"
          data-currency="gbp"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mustrd" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="/">Mustrd</a>
        <ul class="nav navbar-nav navbar-right">
            <li class="item_count"><%= link_to pluralize(current_cart.count, 'item'), current_cart, id: 'cart-link' %></li>
          <% if current_user %>
            <li><%= link_to "Sign out", destroy_user_session_path %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
        <div class="nav-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1" %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <% if @hide_sidebar %>
          <div class="col-lg-12">
        <% else %>
          <div class="col-lg-9">
        <% end %>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <% unless @hide_sidebar %>
          <div class="col-lg-3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        <% end %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/order_notifier/confirmation_email.html.erb
<p>Hi Sam</p>
<p>Thanks for your order! You ordered <%= pluralize @number_of_items, 'item' %>.</p>
<p>We hope you enjoy your order and that we see you again soon on MUSTRD.com</p>
<p>Sincerely</p>
<p>The MUSTRD team</p>

app/views/products/edit.html.erb
<div>
	<h2> Edit product details: </h2>
	<%= render "shared/product_form" %>
</div>

app/views/products/index.html.erb
<% @products.each do |product| %>
	<%= link_to product.name, product %>
	<div class='cart-button'>
		<%= form_for current_cart do |f| %>
			<%= f.hidden_field :product_id, value: product.id %>
			<%= f.submit 'Add to Cart' %>
		<% end %>
	</div>

<% end %>

app/views/products/new.html.erb
<div>
	<h2> New product details: </h2>
	<%= render "shared/product_form" %>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h5><%= @product.description %></h5>
<h5>Quantity: <%= @product.quantity %></h5>
<h5>Price: <%=  @product.formatted_price %></h5>
<h5><%= image_tag @product.image.url, class: 'product_image' %></h5>

<p><%= link_to "Edit product", edit_product_path(@product) %></p>

<p><%= button_to "Delete product", @product, :method=>:delete, data: {confirm: 'Are you sure?'} %></p>

app/views/shared/_product_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
	<%= f.text_field :name, placeholder: 'name' %>
	<%= f.text_field :description, placeholder: 'description' %>
	<%= f.text_field :quantity, placeholder: 'quantity' %>
	<%= f.text_field :price, placeholder: 'price' %>
	<%= f.label :image %>
	<%= f.file_field :image %>
	<%= f.submit %>
<% end %>

app/views/users/poupon.html.erb
<h1>Grey Poupon</h1>
<h3>Get ready to spread!</h3>
<iframe width="560" height="315" src="//www.youtube.com/embed/mqIZa3PTX6c" frameborder="0" allowfullscreen></iframe>

app/views/users/show.html.erb
<h1>@user.name</h1>